docs/AboutUs.md
docs/team/julietteoh.md

resolve #35
Add an image: images/julietteoh.png
Create portfolio page: team/julietteoh.md

Docs: update individual section for About Us

---

docs/UserGuide.md

Resolve #36 
Updated user guide for these commands: ADD, REMOVE, EDIT, FIND, LIST, CLEAR, HELP
Cleaned Git tree by deleting old bad branch and recommiting changes

Docs: update some commands of User Guide

---

docs/UserGuide.md

Docs: add send command to UserGuide

---

docs/team/tjtanjin.md

Add personal portfolio for tjtanjin (initial template, to be updated overtime)
Closes #67

Docs: add initial template for tjtanjin personal portfolio

---

docs/WorkflowGuide.md

Reduce ImPoster icon size in workflow guide.
Closes #72

Docs: reduce imposter icon size to 300px

---

docs/_config.yml

Update _config.yml to correctly reflect information about imPoster on the website.
Closes #83

Docs: update _config.yml with imposter information

---

docs/UserGuide.md

Update user guide features to correctly reflect ImPoster commands usage.
Minor rephrasing done to standardise terms and improve clarity.
Closes #80

Docs: update userguide phrasing and features

---

build.gradle
docs/DeveloperGuide.md
docs/SettingUp.md
docs/UserGuide.md
docs/WorkflowGuide.md
docs/team/ong6.md
docs/team/tjtanjin.md
docs/team/tlylt.md
src/main/java/seedu/us/among/ImPoster.java
src/main/java/seedu/us/among/Main.java
src/main/java/seedu/us/among/logic/commands/ExitCommand.java
src/main/java/seedu/us/among/model/ModelManager.java
src/main/resources/view/MainWindow.fxml
src/test/data/JsonSerializableEndpointListTest/typicalEndpointList.json

Docs: update all instances of ImPoster to imPoster

---

README.md
docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/us/among/logic/parser/ImposterParser.java
src/test/java/seedu/us/among/logic/LogicManagerTest.java

I added 1 user story to the developer's guide, updated the user guide and readme
Closes #95

Bug Fix and Docs: Update documents after refactoring and fix some bugs

---

docs/index.md

Update index.md file to reflect information about imPoster on the main webpage.
Closes #99

Docs: update index to correctly show product information on main webpage

---

build.gradle

Update build.gradle to use correct `mainClassName`.
Closes #119

Refactor: update build.gradle to reflect new package name

---

README.md
docs/DeveloperGuide.md
docs/UserGuide.md

fixes #118 
fixes #115 
Minor bug fixes on documentation.

Fix minor syntax issues within readme & docs

---

docs/TestsToFix.txt
src/main/java/seedu/us/among/model/endpoint/Endpoint.java
src/main/java/seedu/us/among/model/endpoint/UniqueEndpointList.java
src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
src/test/java/seedu/us/among/model/EndpointListTest.java
src/test/java/seedu/us/among/model/endpoint/EndpointTest.java
src/test/java/seedu/us/among/model/endpoint/UniqueEndpointListTest.java

I helped to fix some test cases that were removed from the code previously. 
Important to note: in our current code, only endpoints with the same method AND address AND tags will be seen as equal and throw an error.
I also added docs/TestsToFix.txt, which states the remaining files which have test cases to be fixed, such that future test fixers/bug fixers will have an easier time locating the files.
Resolves #126

Bug: Fix test cases

---

src/main/java/seedu/us/among/commons/util/JsonUtil.java
src/main/java/seedu/us/among/commons/util/StringUtil.java
src/main/java/seedu/us/among/logic/commands/CommandResult.java
src/main/java/seedu/us/among/logic/commands/SendCommand.java
src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
src/main/java/seedu/us/among/model/endpoint/Response.java
src/main/java/seedu/us/among/ui/MainWindow.java
src/main/java/seedu/us/among/ui/ResultDisplay.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/ResultDisplay.fxml

fixes: #134
- highlighting the method, status, and time taken for the API responses
- styling is not yet final but could be helpful to merge this initial version so that team members can visualize it when working on it today
- more cosmetic changes and code refactoring will be done as a follow up to this PR
- other display decisions to be discussed in the coming team meeting
---

Display result update

---

src/main/java/seedu/us/among/logic/commands/AddCommand.java
src/main/java/seedu/us/among/logic/commands/EditCommand.java
src/main/java/seedu/us/among/logic/commands/SendCommand.java
src/main/java/seedu/us/among/logic/parser/AddCommandParser.java
src/main/java/seedu/us/among/logic/parser/CliSyntax.java
src/main/java/seedu/us/among/logic/parser/EditCommandParser.java
src/main/java/seedu/us/among/logic/parser/ParserUtil.java
src/main/java/seedu/us/among/model/endpoint/Data.java
src/main/java/seedu/us/among/model/endpoint/Endpoint.java
src/main/java/seedu/us/among/model/endpoint/header/Header.java
src/main/java/seedu/us/among/model/util/SampleDataUtil.java
src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
src/main/java/seedu/us/among/storage/JsonAdaptedHeader.java
src/main/java/seedu/us/among/ui/EndpointCard.java
src/main/resources/view/EndpointListCard.fxml
src/test/java/seedu/us/among/logic/LogicManagerTest.java
src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
src/test/java/seedu/us/among/logic/parser/AddCommandParserTest.java
src/test/java/seedu/us/among/logic/parser/ImposterParserTest.java
src/test/java/seedu/us/among/storage/JsonAdaptedEndpointTest.java
src/test/java/seedu/us/among/testutil/EndpointBuilder.java
src/test/java/seedu/us/among/testutil/TypicalEndpoints.java

Data stores a string (does not check it if it is a json)
Header mimics tags (and need to be improved)
Things to update:
Fix all test cases (I commented out some)
Currently having a data field is mandatory, but please change it so that it is optional
The header field is adapted straight from tags and needs more refinement
Closes #144

Commands: Add a minimally working data and header field.

---

src/main/java/seedu/us/among/ui/MainWindow.java

- Help window was not opening when the help command is issued.
Fixes #164

Fix issue of help-window not opening for help command

---

src/main/java/seedu/us/among/model/util/SampleDataUtil.java

- update the examples to include a few API endpoints
- this will be seen when users use imPoster for the first time, i.e. you can mimic it by deleting your imposter.json file in the data folder
- future updates will include more examples of type POST etc
Fixes : #156

Fix sample data for first time users

---

src/main/java/seedu/us/among/ui/CommandBox.java

Minor fix to auto-focus issue for send command on command box.
Fixes #176

Fix: fix a bug where command box is not auto-focused after send command

---

src/main/java/seedu/us/among/logic/endpoint/Request.java

Add missing line of code for post request body data to be sent correctly.
Fixes #178

Fix: fix bug with post request body data not being sent

---

docs/DeveloperGuide.md
docs/WorkflowGuide.md

- add a link in developer guide to workflow guide
- also fix the workflow guide page title
Fixes #175

Include workflow guide

---

src/main/resources/view/ResultDisplay.fxml

Maximise result display to remove redundant right panel.
Resolves #205

Refactor: extend result display instead of having extra right panel in UI

---

src/main/java/seedu/us/among/logic/endpoint/DeleteRequest.java
src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java

Add support for delete request.
Closes #194

Feat: add support for delete request

---

src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
src/main/java/seedu/us/among/logic/endpoint/PutRequest.java
src/main/java/seedu/us/among/logic/endpoint/Request.java

Add support for PUT request.
Note: 
- There's this very strange checkstyle error that I have flagged out and bypassed in code.
- @tlylt Please feel free to merge it after you reviewed and feel there is nothing else to change.
Closes #231

Feat: add support for put request

---

src/main/java/seedu/us/among/logic/commands/RunCommand.java
src/main/java/seedu/us/among/model/endpoint/Endpoint.java
src/main/java/seedu/us/among/model/endpoint/Response.java

- update to the following for showing of endpoints that have yet to be tested
- meanwhile also fixed run command's exception handling
Fixes #228

Fix display of endpoint and response

---

src/main/java/seedu/us/among/commons/util/HeaderUtil.java
src/main/java/seedu/us/among/logic/endpoint/DeleteRequest.java
src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
src/main/java/seedu/us/among/logic/endpoint/PostRequest.java
src/main/java/seedu/us/among/logic/endpoint/PutRequest.java
src/main/java/seedu/us/among/logic/endpoint/Request.java

Certain parts are duplicated and repeated
Let's fix some of the violations and improve code quality in terms of
extracting out smaller methods and make minor adjustments to how request
is executed.
This is so that further inheritance and reference to the request code
can reduce the amount of lines that are previously required but now
abstracted away.
Fixes #233

Refactor request related code

---

src/main/java/seedu/us/among/logic/parser/ToggleCommandParser.java
src/main/java/seedu/us/among/model/endpoint/Method.java
src/main/java/seedu/us/among/model/endpoint/MethodType.java
src/main/java/seedu/us/among/ui/ThemeType.java

Came across a [website](https://www.stubbornjava.com/posts/java-enum-lookup-by-name-or-field-without-throwing-exceptions) describing better use of enums. Ours was listed as an example that could be improved and thought to apply it to our codebase.
Closes #248

Refactor: tidy up code to improve enum code readability and efficiency

---

src/main/java/seedu/us/among/logic/parser/SendCommandParser.java
src/main/java/seedu/us/among/model/util/SampleDataUtil.java
src/test/java/seedu/us/among/logic/commands/SendCommandTest.java
src/test/java/seedu/us/among/logic/parser/SendCommandParserTest.java
src/test/java/seedu/us/among/testutil/TypicalEndpoints.java
src/test/java/seedu/us/among/testutil/TypicalIndexes.java

Add test cases for SendCommand and SendCommandParser.
Closes #240 
Closes #241

Chore: add test cases for SendCommand and SendCommandParser

---

src/main/java/seedu/us/among/logic/commands/RunCommand.java
src/main/java/seedu/us/among/logic/commands/SendCommand.java
src/main/java/seedu/us/among/model/endpoint/Endpoint.java

Minor refactoring to move a common method within sendCommand and runCommand into endpoint instead.

Refactor code for send & run command

---

docs/UserGuide.md

Add show command details in user guide

---

src/main/java/seedu/us/among/ui/ResultDisplay.java

Add reason phrase in API response to user.
Resolves #209

Refactor: include reasonphrase in response to user

---

src/test/java/seedu/us/among/model/endpoint/DataTest.java
src/test/java/seedu/us/among/model/endpoint/ResponseTest.java
src/test/java/seedu/us/among/model/header/HeaderTest.java
src/test/java/seedu/us/among/model/tag/TagTest.java

Add test cases for data, header and response attributes of endpoint.
Also added additional test cases for tag attribute.
Resolves #269

Add attributes test

---

src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
src/main/java/seedu/us/among/logic/endpoint/HeadRequest.java
src/main/java/seedu/us/among/logic/endpoint/OptionsRequest.java
src/main/java/seedu/us/among/logic/endpoint/PatchRequest.java

Add support for head, options and patch request. I will double check and tidy up these code again if necessary.
Closes #273

Add remaining requests

---

src/test/java/seedu/us/among/logic/LogicManagerTest.java
src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
src/test/java/seedu/us/among/logic/commands/EditEndpointDescriptorTest.java
src/test/java/seedu/us/among/logic/parser/AddCommandParserTest.java
src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java

From my eyeballing, the main test case left to fix is NameContainsKeywordsPredicateTest.java

Fix test cases mainly in AddCommandPaserTest and EditCommandPaserTest

---

docs/TestsToFix.txt
src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java
src/test/java/seedu/us/among/logic/parser/ParserUtilTest.java
src/test/java/seedu/us/among/model/endpoint/EndpointTest.java
src/test/java/seedu/us/among/model/endpoint/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/us/among/storage/JsonAdaptedEndpointTest.java
src/test/java/seedu/us/among/testutil/EndpointUtil.java

Some test cases do not fit their test name, after the deletion of email and phone. I tried to fix and add back many of these test cases.

Testing: Add test cases

---

src/main/java/seedu/us/among/model/util/SampleDataUtil.java
src/test/data/JsonSerializableEndpointListTest/typicalEndpointList.json
src/test/java/seedu/us/among/logic/endpoint/DeleteRequestTest.java
src/test/java/seedu/us/among/logic/endpoint/GetRequestTest.java
src/test/java/seedu/us/among/logic/endpoint/HeadRequestTest.java
src/test/java/seedu/us/among/logic/endpoint/OptionsRequestTest.java
src/test/java/seedu/us/among/logic/endpoint/PatchRequestTest.java
src/test/java/seedu/us/among/logic/endpoint/PostRequestTest.java
src/test/java/seedu/us/among/logic/endpoint/PutRequestTest.java
src/test/java/seedu/us/among/testutil/TypicalEndpoints.java

Increase test coverage by adding test cases for Request classes.
Closes #278

Chore: add test cases for Request classes

---

src/main/java/seedu/us/among/logic/commands/RunCommand.java
src/main/java/seedu/us/among/logic/commands/SendCommand.java
src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
src/main/java/seedu/us/among/logic/endpoint/Request.java
src/main/java/seedu/us/among/model/endpoint/Endpoint.java
src/test/java/seedu/us/among/logic/commands/RunCommandTest.java

Read for details: https://github.com/nus-cs2103-AY2021S2/forum/issues/240#issuecomment-800513614
Fixes: #289

Refactor based on Juliet's suggestion on LOD

---

src/test/java/seedu/us/among/model/endpoint/AddressTest.java
src/test/java/seedu/us/among/model/endpoint/DataTest.java
src/test/java/seedu/us/among/model/endpoint/MethodTest.java
src/test/java/seedu/us/among/model/header/HeaderTest.java
src/test/java/seedu/us/among/model/tag/TagTest.java

Update some improper values for test and add a few new test cases for attributes under `Endpoint`.
Closes #290

Fix: fix some improper test information and add a few more cases

---

src/main/java/seedu/us/among/model/endpoint/Endpoint.java
src/main/java/seedu/us/among/ui/ResultDisplay.java

Fix bug that shows 2 timings in the response meta.
Fixes #293

Fix: fix extra time field in response meta

---

src/main/java/seedu/us/among/ui/HelpWindow.java
src/main/java/seedu/us/among/ui/UserGuide.java
src/main/resources/view/HelpWindow.fxml
src/test/java/seedu/us/among/ui/UserGuideTest.java

- include a quick intro to RESTful API youtube link
- build a table view of our Command summary
- work in progress
Fixes: #151

Improve help command result

---

src/main/resources/view/DarkTheme.css
src/main/resources/view/Extensions.css
src/main/resources/view/ImposterTheme.css
src/main/resources/view/LightTheme.css

Made the UI look good 
Fixes #284

UI: Improved UI and bug fixes

---

build.gradle
src/main/java/seedu/us/among/logic/commands/RunCommand.java
src/main/java/seedu/us/among/logic/commands/SendCommand.java
src/main/java/seedu/us/among/model/endpoint/Endpoint.java

- fix comments for isSameEndpoint
- add logging for sendCommand and runCommand
- added enable assertion in gradle file
Fixes: #301

Defensive send run

---

src/main/java/seedu/us/among/logic/commands/ShowCommand.java
src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
src/main/java/seedu/us/among/logic/parser/SendCommandParser.java
src/main/java/seedu/us/among/logic/parser/ShowCommandParser.java
src/test/java/seedu/us/among/logic/parser/RunCommandParserTest.java

Add assert and logging for run and send parsers

---

src/main/java/seedu/us/among/commons/core/GuiSettings.java
src/main/java/seedu/us/among/ui/MainWindow.java
src/test/java/seedu/us/among/model/ModelManagerTest.java
src/test/java/seedu/us/among/storage/JsonUserPrefsStorageTest.java
src/test/java/seedu/us/among/storage/StorageManagerTest.java

Application theme now saves on exit and loads properly on start.
Fixes #297

Fix: application theme now saves and loads properly

---

src/main/java/seedu/us/among/logic/commands/RunCommand.java
src/main/java/seedu/us/among/logic/commands/SendCommand.java
src/main/java/seedu/us/among/logic/request/PatchRequest.java
src/main/java/seedu/us/among/logic/request/PostRequest.java
src/main/java/seedu/us/among/logic/request/PutRequest.java
src/main/java/seedu/us/among/logic/request/Request.java

Add catching of exception for edge cases in invalid URLs.
Also add body data for patch request.
Fixes #336

Fix: fix invalid url request

---

src/main/java/seedu/us/among/commons/core/Messages.java
src/main/java/seedu/us/among/logic/commands/RunCommand.java
src/main/java/seedu/us/among/logic/commands/SendCommand.java
src/main/java/seedu/us/among/logic/commands/ShowCommand.java
src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
src/test/java/seedu/us/among/logic/commands/RunCommandTest.java
src/test/java/seedu/us/among/logic/commands/ShowCommandTest.java

Show & run command coverage

---

src/main/java/seedu/us/among/ImPoster.java

Update app version in ImPoster for trial release.
Closes #348

Chore: update app version in ImPoster

---

src/main/java/seedu/us/among/logic/commands/SendCommand.java
src/test/java/seedu/us/among/logic/commands/SendCommandTest.java
src/test/java/seedu/us/among/logic/commands/ToggleCommandTest.java
src/test/java/seedu/us/among/logic/parser/SendCommandParserTest.java
src/test/java/seedu/us/among/logic/parser/ToggleCommandParserTest.java

Add more test cases for `Send` and `Toggle` command/parser.
Closes #346

Chore: add test cases for Send and Toggle command/parser

---

docs/DeveloperGuide.md

Place logo in correct position and size.
Standardise cover page with user guide.
Fixes #354

Fix: fix developer guide cover page

---

src/main/java/seedu/us/among/logic/parser/ParserUtil.java
src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
src/main/java/seedu/us/among/model/endpoint/Address.java
src/test/java/seedu/us/among/logic/parser/ImposterParserTest.java
src/test/java/seedu/us/among/logic/parser/RunCommandParserTest.java

Fix test cases for send, run and imposterParser

---

src/main/java/seedu/us/among/ui/ResultDisplay.java

Refactor: use square unicode chars for response title

---

src/main/resources/view/CommandBox.fxml
src/main/resources/view/DarkTheme.css
src/main/resources/view/EndpointListPanel.fxml
src/main/resources/view/ImposterTheme.css
src/main/resources/view/LightTheme.css
src/main/resources/view/ResultDisplay.fxml

Feat: add outline to focused component for clarity

---

docs/DeveloperGuide.md

Add use cases to reflect newly added `toggle`, `show` and <kbd>ctrl</kbd> + <kbd>d</kbd> functionalities.
Add preface to `send/run` feature and `request` feature.
Minor updates to appendix/NFR.
Closes #389

Docs: minor content update to developer guide

---

docs/AboutUs.md

Fix broken image links for icons.
Fixes #391

Fix: fix image links for icons in AboutUs

---

docs/team/julietteoh.md
src/main/java/seedu/us/among/model/endpoint/Address.java
src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
src/main/java/seedu/us/among/ui/MainWindow.java
src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
src/test/java/seedu/us/among/logic/commands/EditEndpointDescriptorTest.java
src/test/java/seedu/us/among/logic/parser/CommandParserTestUtil.java
src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java
src/test/java/seedu/us/among/testutil/EditEndpointDescriptorBuilder.java

Test: Edit remove test cases

---

README.md
docs/index.md

Updated README image and add UI image to index page.
Closes #429

Docs: minor update to readme and index page

---

docs/UserGuide.md

Update some GET APIs

---

src/main/java/seedu/us/among/logic/commands/ToggleCommand.java

Chore: update togglecommand message to include imposter and material themes

---

src/main/java/seedu/us/among/logic/request/EndpointCaller.java
src/main/java/seedu/us/among/logic/request/Request.java

Fix: fix a bug where null exception results in looping gif

---

docs/DeveloperGuide.md

Add skeleton for **Instructions for Manual Testing** and **Effort** to DG appendix. Both needs to be heavily updated soon.
Closes #452

Docs: add required sections to appendix

---

src/main/java/seedu/us/among/ImPoster.java

Updated the version number according to DevOps guide. @ong6, @NightRaven49 take note to update it if you guys are releasing the new versions.
Fixes #456

Update version number

---

src/main/resources/view/MainWindow.fxml
src/test/java/seedu/us/among/testutil/TypicalEndpoints.java

Remove to-do
Update the main theme to material

Small changes

---

docs/UserGuide.md

Docs: tidy up user guide for PE dry run

---

src/main/java/seedu/us/among/commons/core/GuiSettings.java
src/main/java/seedu/us/among/commons/core/Messages.java
src/main/java/seedu/us/among/ui/ResultDisplay.java

Fixes #516
Fixes the UI colour issues.

Fixes #516, Update GUI theme loading

---

docs/team/tjtanjin.md

Docs: fix minor details in tjtanjin ppp

---

docs/UserGuide.md

Fix the following based on PE-D feedback:
- Add link to JSON data format in parameters table
- Add description to JSON data examples
- Specify when data file is created
- Standardise URI terms to URL
Fixes #497 
Fixes #506 
Fixes #515 
Fixes #520

Docs: touchup UG details based on PE-D feedback

---

docs/UserGuide.md

Docs: Fix formatting and broken hyperlink in UG

---

src/main/java/seedu/us/among/commons/core/GuiSettings.java
src/main/java/seedu/us/among/model/UserPrefs.java
src/main/java/seedu/us/among/ui/ResultDisplay.java

Edit: help double check this thanks.
Fixes #547

Fix: fix themed gifs not loading correctly

---

docs/Gemfile.lock
docs/UserGuide.md
src/main/java/seedu/us/among/logic/commands/EditCommand.java
src/main/java/seedu/us/among/model/endpoint/Address.java
src/main/java/seedu/us/among/model/endpoint/Endpoint.java
src/main/java/seedu/us/among/model/tag/Tag.java

Fixes #531 
Fixes #525
Fixes #489
Fixes #476
Fixes #473
User guide improvements again. 
Nicer header output.
Other nicer error messages.

Addressing more bugs

---

docs/UserGuide.md
src/main/java/seedu/us/among/logic/commands/EditCommand.java
src/main/java/seedu/us/among/model/Model.java
src/main/java/seedu/us/among/model/ModelManager.java
src/test/java/seedu/us/among/logic/commands/AddCommandTest.java
src/test/java/seedu/us/among/logic/commands/EditCommandTest.java

Edit does not refresh the endpoint list.

---

docs/UserGuide.md
src/main/java/seedu/us/among/logic/commands/EditCommand.java
src/main/java/seedu/us/among/logic/commands/RemoveCommand.java
src/main/java/seedu/us/among/logic/commands/SendCommand.java
src/main/java/seedu/us/among/logic/parser/RemoveCommandParser.java
src/main/java/seedu/us/among/logic/parser/SendCommandParser.java
src/test/java/seedu/us/among/logic/LogicManagerTest.java
src/test/java/seedu/us/among/logic/commands/RemoveCommandTest.java
src/test/java/seedu/us/among/logic/commands/SendCommandTest.java
src/test/java/seedu/us/among/logic/parser/RemoveCommandParserTest.java
src/test/java/seedu/us/among/logic/parser/SendCommandParserTest.java
src/test/java/seedu/us/among/logic/parser/ShowCommandParserTest.java

- fixes #511, fixes #523, fixes #518, fixes #512
- also update the run command syntax in UG (-x and -u are in fact compulsory fields)
- similar update to test cases in order to adapt to the new error message format

Fix index error for remove and send command

---

docs/UserGuide.md
src/main/java/seedu/us/among/logic/commands/ListCommand.java

Edit list command message to be less wordy

---

docs/UserGuide.md

Improve find command in UG

---

docs/UserGuide.md
src/main/java/seedu/us/among/commons/core/Messages.java
src/main/java/seedu/us/among/logic/parser/ParserUtil.java
src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
src/main/java/seedu/us/among/model/endpoint/Address.java
src/test/java/seedu/us/among/logic/parser/AddCommandParserTest.java
src/test/java/seedu/us/among/logic/parser/RunCommandParserTest.java

Fixes #495: added a note about URL validity in UG
Fixes #496, fixes #514: added more general error message

Update RunCommandParser and fix relevant error messages

---

docs/UserGuide.md
docs/team/julietteoh.md
src/main/java/seedu/us/among/commons/core/Messages.java
src/main/java/seedu/us/among/logic/commands/AddCommand.java
src/main/java/seedu/us/among/logic/commands/EditCommand.java
src/main/java/seedu/us/among/logic/commands/FindCommand.java
src/main/java/seedu/us/among/logic/commands/RunCommand.java
src/main/java/seedu/us/among/logic/parser/EditCommandParser.java
src/main/java/seedu/us/among/model/endpoint/Endpoint.java
src/main/java/seedu/us/among/model/endpoint/Response.java
src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java

Closes #567 
Closes #561
@tlylt can u help me check if this is the intended UI output, especially the index errors?
show valid
edit valid
add valid
ERROR MESSAGE BELOW:
add
edit
run
find 
edit index = 0
edit index = -1000
edit index = 20
edit index = 10000000000

Fix error messages

---

src/main/java/seedu/us/among/commons/core/GuiSettings.java
src/main/java/seedu/us/among/commons/core/Messages.java
src/main/java/seedu/us/among/logic/commands/AddCommand.java
src/main/java/seedu/us/among/logic/commands/CommandResult.java
src/main/java/seedu/us/among/logic/commands/EditCommand.java
src/main/java/seedu/us/among/logic/commands/ShowCommand.java
src/main/java/seedu/us/among/model/endpoint/Endpoint.java
src/main/java/seedu/us/among/model/endpoint/Response.java
src/main/java/seedu/us/among/ui/MainWindow.java
src/main/java/seedu/us/among/ui/ResultDisplay.java
src/test/java/seedu/us/among/logic/commands/AddCommandIntegrationTest.java
src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
src/test/java/seedu/us/among/storage/JsonUserPrefsStorageTest.java

`show 1 `
displays: 
`add -x get -u url` 
displays:
`send 1` 
displays: 
`show 1` after sending 
displays:

UI: Adding flowPane display for add, edit and show

---

docs/UserGuide.md
src/main/java/seedu/us/among/logic/commands/AddCommand.java
src/main/java/seedu/us/among/logic/commands/EditCommand.java
src/main/java/seedu/us/among/logic/commands/FindCommand.java
src/main/java/seedu/us/among/logic/commands/RunCommand.java
src/main/resources/view/HelpWindow.fxml

Fixes #570, see details in the issue.

Update usage of GET and edit examples

---

src/main/java/seedu/us/among/ImPoster.java

Chore: update release version to match v1.4

---

src/main/resources/view/MainWindow.fxml

Update minimun size

---

docs/UserGuide.md

- Update includes any inconsistencies such as the use of full stop and minor edits on phrasing.
- Screenshot under 3 Quickstart still shows the annotated one, are we replacing it? Just a reminder if this is already known.
- The use of the term `endpoint list` is not very standardized, is it endpoint list, or saved endpoint list, or endpoint list panel. perhaps the next person who checks the UG can assist in double-checking on this.
- @tjtanjin I think now the UG is not edited with the line breaks in mind, so may need your kind help to fix those when screenshots are all updated.
- Fixes #590 (That's all the time I can give to UG, the rest help pls 🆘 )

Edit UG to fix any minor issues

---

docs/UserGuide.md

Quick fix UG

---

docs/team/tlylt.md

Minor edit on my PPP page to fix the title issues.

Fix formatting

---

docs/team/tlylt.md

Minor update to my ppp page

---

docs/DevOps.md
docs/DeveloperGuide.md
docs/Testing.md
docs/index.md

- Minor clean up for Documentation, logging, testing, configuration, dev-ops
- Fixes #598 
- Fixes #587

Clean up for DG

---

docs/DeveloperGuide.md

Fix some formatting/descriptions in use cases and NFR.
Closes #592

Docs: tidy up use cases and NFR

---

docs/DeveloperGuide.md
docs/WorkflowGuide.md

Workflow guide -> made it more accurate
Appendix -> used User guide style, without the colors.

Update appendix E and F

---

docs/DeveloperGuide.md

Docs: update DG test cases and resize diagrams

---

src/main/java/seedu/us/among/logic/commands/AddCommand.java
src/main/java/seedu/us/among/logic/commands/CommandResult.java
src/main/java/seedu/us/among/logic/commands/EditCommand.java
src/main/java/seedu/us/among/logic/commands/ShowCommand.java
src/main/java/seedu/us/among/ui/EndpointListPanel.java
src/main/java/seedu/us/among/ui/MainWindow.java
src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java

Fixes #483 
Closes #589 
Now add, edit, show and send will point to the Endpoint that they are using
Remove and run will unfocus the endpoint list to reduce confusion.
Sample:

UI: Update endpoint after show command.

---

docs/DeveloperGuide.md

DG: Appendix H implementation

---

README.md
docs/DeveloperGuide.md

Docs: Furnish up DG

---

docs/DeveloperGuide.md

can preview print from here: https://nightraven49.github.io/tp/DeveloperGuide.html

Docs: DG final revision

---

docs/DeveloperGuide.md

Docs: update effort appendix and request feature

---

docs/team/tjtanjin.md

Minor changes to DG section.
Fixes #636

Docs: finalise tjtanjin PPP

---

src/main/java/seedu/us/among/Main.java
src/main/java/seedu/us/among/commons/util/StringUtil.java
src/main/java/seedu/us/among/model/endpoint/MethodType.java
src/main/java/seedu/us/among/ui/ResultDisplay.java
src/main/java/seedu/us/among/ui/ThemeType.java

As described in title. Changes only done to code comments so no need for any re-release of the JAR.
Closes #641

Chore: update code comments to adhere to code reuse policy
