- scripts/sync.sh
Add script to easily sync local, remote and team repositories.
Usage on terminal:
`sh sync [local branch to sync]`
If a branch is not specified, the default branch used will be `master`.
Closes #43
> Chore: add script to easily sync repositories

- docs/DeveloperGuide.md
Tidy up developer guide to standardise the following:
1) No fullstops after each bullet point
2) API route -> API endpoint
Add user stories and use cases.
Miscellaneous updates as well to phrasing, NFR and glossary.
Closes #70
> Docs: update developer guide and add user stories and use cases

- .githooks/pre-commit
Add pre-commit hook to ensure checkstyle test and test cases are passing before a commit is allowed. This will achieve the following:
- In the event that github actions fail like earlier today, commits still minimally pass local tests and checks (which should translate to passing the CI on the remote as well).
- Reduce unnecessary commits clutter for fixing checkstyle or test errors.
- There is a limit to github actions on a free organisation and although we are unlikely to hit it, this still reduces the use of github actions and is generally good practice.
To use, update the master branch and simply run the command in the project repository (similar instruction is given at the top of the file in comments as well):
`git config --local core.hooksPath .githooks/`
Future `git commit` will …
> Chore: add githook to ensure checkstyle and test passes locally before commit

- docs/UserGuide.md
Tidy up user guide template.
Minor reductions to keep the guide clean and simple:
- Removed descriptions for examples - to reconsider how to better add those in a future update.
Closes #103
> Docs: tidy up and update user guide

- README.md
Resize imPoster icon.
Centralise CI and Codecov badges.
Closes #116
> Docs: resize imposter icon and centralise badges

- src/main/resources/view/MainWindow.fxml
Add basic template for new UI that is more relevant to our product.
For ease of review, the skeleton of the new UI looks like this:
Closes #131
> Feat: add basic template for new UI

- src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
- src/main/java/seedu/us/among/model/endpoint/Response.java
- src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
- src/main/java/seedu/us/among/storage/JsonAdaptedResponse.java
fixes #133 
- A small update to get me into the flow lol
- Track the response time in seconds and store it as part of the response model
- right now it is simply displayed along with other response details (see below)
> Add time taken as an attribute of response

- src/main/java/seedu/us/among/commons/util/JsonUtil.java
- src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
fixes #138 
- include a util method to convert HTTP entity string into a pretty JSON string
- the pretty formatted string will be stored as part of the response
- this allows easy retrieval and printing of the main response body later on
- the main difference between the stored string vs the previous version is that `\n` is added accordingly so that when printing it is properly separated. I think this may add a little bit in term of storage space but the difference is very minor and can be safely ignored.
- for now, it is printed in the display as it is with the other meta information, which I will tackle next
> Refactor response to store and display pretty printed json string

- src/main/java/seedu/us/among/logic/commands/SendCommand.java
- src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
- src/main/java/seedu/us/among/ui/CommandBox.java
- src/main/java/seedu/us/among/ui/EndpointListPanel.java
- src/main/java/seedu/us/among/ui/MainWindow.java
This PR does not add a loading spinner but it minimally updates the UI with a visible progress message during the execution of a command. I propose that a new issue be created for adding loading spinner as an enhancement given there are many other more important functionalities to work on.
This PR addresses the following:
- Command executions are now handled on a new thread, thus free-ing up the UI
- A simple progress message (also handled on a new thread) is now shown to the user during command execution
An example of the `send 7` command:
I am of the opinion that there can still be further improvements to its implementation/code quality. Kindly advice if anyone has suggestions.
Closes #140
> Feat: add thread to handle UI update for showing command execution progress

- src/main/java/seedu/us/among/commons/util/StringUtil.java
- src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
- src/main/java/seedu/us/among/model/endpoint/Response.java
- Bug fix as requested by @JulietTeoh 
- Response time was added with the word "seconds" in the model's getResponse() but it is causing duplication when updating the timing
- Change to saving the response time as a string with "seconds". So now response time will be saved like this: "1.223 seconds"
Fixes #159
> Fix response time saving bug

- src/main/java/seedu/us/among/ui/CommandBox.java
- src/main/java/seedu/us/among/ui/EndpointListPanel.java
- src/main/java/seedu/us/among/ui/MainWindow.java
Resolved the issue with exit command not closing application.
Resolved the 1 second lag experienced when entering command after the UI threading update.
Add disabling of command line upon a successful input to prevent users from spamming input (which can throw an error due to excessive thread creation).
Add a quick fix for remove command threading issue as well.
Fixes #158
> Fix: fix exit command bug along with ui lag and spam input

- src/main/java/seedu/us/among/commons/util/HeaderUtil.java
- src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
- src/main/java/seedu/us/among/logic/endpoint/PostRequest.java
- src/main/java/seedu/us/among/logic/endpoint/Request.java
Add support for POST request. While doing so, the following changes were made:
- Abstract the bulk of send request logic (including timing) from `GetRequest` into `Request` class
- Abstract setting of headers and data into `Request` class
- Add a HeaderUtil class to parse header information
With this PR, post request is integrated with the header and data field from endpoint as well. That is, a correctly added post request should now work.
Closes #167
> Feat: add support for post request

- src/main/java/seedu/us/among/ui/ResultDisplay.java
Add variation of color to response meta depending on status code:
- 200s  - green (success)
- 300s - yellow (redirect)
- 400s - red (client error)
- 500s - red (server error)
A darker shade is also used now so the white text is much more readable.
Closes #184
> Feat: add different color to response meta based on status code

- src/main/java/seedu/us/among/logic/Logic.java
- src/main/java/seedu/us/among/logic/LogicManager.java
- src/main/java/seedu/us/among/logic/commands/Command.java
- src/main/java/seedu/us/among/logic/commands/SendCommand.java
- src/main/java/seedu/us/among/logic/endpoint/Request.java
- src/main/java/seedu/us/among/logic/endpoint/exceptions/RequestException.java
- src/main/java/seedu/us/among/ui/CommandBox.java
- src/main/java/seedu/us/among/ui/MainWindow.java
- src/test/java/seedu/us/among/logic/LogicManagerTest.java
- src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
In addressing the uncaught request exceptions, the following changes have been made:
- Add `RequestException` class to deal with 4 different exceptions thrown when sending a request.
- Timeout implemented for all requests, currently set to 1 minute.
Fixes #187
> Fix: add handling of exceptions when sending request

- src/main/java/seedu/us/among/logic/commands/SendCommand.java
- src/main/java/seedu/us/among/logic/endpoint/Request.java
HTML responses are currently caught as other exceptions (e.g. json parse exception). This PR does the following:
- Show HTML responses correctly
- Minor refactor to Request#execute code for readability
Fixes #191
> Fix: add proper catch for html response

- src/main/java/seedu/us/among/commons/util/HeaderUtil.java
- src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
- src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
- src/main/java/seedu/us/among/logic/endpoint/PostRequest.java
- src/main/java/seedu/us/among/logic/endpoint/Request.java
Add a check when parsing header to catch invalid headers and throw a `RequestException`.
Fixes #198
> Fix: add a check when parsing headers and catch invalid headers

- src/main/java/seedu/us/among/commons/util/HeaderUtil.java
- src/main/java/seedu/us/among/logic/commands/AddCommand.java
- src/main/java/seedu/us/among/logic/parser/AddCommandParser.java
- src/main/java/seedu/us/among/logic/parser/CliSyntax.java
- src/main/java/seedu/us/among/logic/parser/ImposterParser.java
- src/main/java/seedu/us/among/logic/parser/ParserUtil.java
- src/main/java/seedu/us/among/model/endpoint/Data.java
- src/main/java/seedu/us/among/model/endpoint/Endpoint.java
- src/main/java/seedu/us/among/model/endpoint/header/Header.java
- src/main/java/seedu/us/among/model/tag/Tag.java
- src/main/java/seedu/us/among/ui/CommandBox.java
- src/main/java/seedu/us/among/ui/EndpointCard.java
- src/test/java/seedu/us/among/testutil/TypicalEndpoints.java
Fixes #155 
Fixes #157 
Updated Imposter Parser, can take in command in any letter case now: e.g. ADD and aDD are all accepted. 
Updated CLISyntax, users must now put a space after their command identifier. 
Updated Add command, changed error message and cleaned things up 
Updated Header, must enclose the string in `"key: value"` format.
Updated Data, must enclose string in {key: value} format. //to-do let this only take in json format.
As of now, the only commands not done is `find` and `help` commands.
> Model and Commands: Wrapped things up and fixed many bugs. 

- src/main/java/seedu/us/among/logic/commands/RunCommand.java
- src/main/java/seedu/us/among/logic/parser/ImposterParser.java
- src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
Without RunCommand, users have to rely on saving API endpoints then
running it by invoking the send command.
Let's add a run command that allows users to run API requests without
saving them.
This will improve user experience in terms of quickly testing out an
API endpoint.
More refactoring to the code is needed but due to big PRs soon to be
made by TJ and JX, I shall not make any potential breaking changes in
this PR in terms of code organisation.
Fixes #152
> Add RunCommand ability

- src/main/java/seedu/us/among/logic/commands/SendCommand.java
- src/main/java/seedu/us/among/logic/endpoint/Request.java
- src/main/java/seedu/us/among/ui/MainWindow.java
Add a keyboard shortcut for users to cancel a request. The code has been trimmed down a lot and was not as complicated as I initially thought it would be. The changes are as such:
- `MainWindow` now looks out for a `ctrl + c` keyboard event in the time period when a player is making an API call.
- `Request` httpclient attribute is directly accessible from the keyboard event to close it, throwing an exception that is caught within `SendCommand`. @tlylt This should affect `RunCommand` as well, I have yet to update that portion of the code but you may be interested to take a look.
- The threads are automatically killed upon the interrupt (at least based on current observations).
Resolves #141 
Resolves #188
> Feat: add keyboard shortcut for user to cancel request

- src/main/java/seedu/us/among/logic/commands/SendCommand.java
Properly match exceptions and make a note to double-check them again.
Also did minor improvements to error message details.
Fixes #220
> Fix: fix mismatched exceptions for request errors

- src/main/java/seedu/us/among/logic/commands/ShowCommand.java
- src/main/java/seedu/us/among/logic/parser/ImposterParser.java
- src/main/java/seedu/us/among/logic/parser/ShowCommandParser.java
- src/test/java/seedu/us/among/logic/commands/ShowCommandTest.java
- src/test/java/seedu/us/among/logic/parser/ShowCommandParserTest.java
Without show command, users are unable to view the details of the endpoints saved.
Let's add a show command whereby users can specify the index to view the
the particular endpoint on the display panel on the right.
Show command takes the form of show 1.
Fixes #203 
Fixes #202
> Add show command

- src/main/java/seedu/us/among/logic/commands/RunCommand.java
- src/main/java/seedu/us/among/model/util/SampleDataUtil.java
- src/test/java/seedu/us/among/logic/commands/RunCommandTest.java
- src/test/java/seedu/us/among/logic/parser/RunCommandParserTest.java
Regression might occur without proper testing.
Let's add test cases for both RunCommand and RunCommandParser.
This will enforce functionality of RunCommand & RunCommandParser to be
in working condition.
Fixes: #224 
Fixes: #225
> Add test for RunCommand & RunCommandParser

- src/main/java/seedu/us/among/commons/util/StringUtil.java
- src/main/java/seedu/us/among/logic/commands/CommandResult.java
- src/main/java/seedu/us/among/logic/commands/ToggleCommand.java
- src/main/java/seedu/us/among/logic/parser/ImposterParser.java
- src/main/java/seedu/us/among/logic/parser/ToggleCommandParser.java
- src/main/java/seedu/us/among/ui/MainWindow.java
- src/main/java/seedu/us/among/ui/ThemeType.java
- src/main/resources/view/LightTheme.css
Add new toggle command for user to choose the application theme. The following changes were made:
- Toggle command added, usage is straightforward (e.g. `toggle light`).
- Adding of new themes has been made easy, it takes only the following two steps:
1) Go within `seedu.us.among.ui.ThemeType` and add your new theme to the enum.
2) Add your new theme file under `resources/view` (e.g. `TestTheme.css`).
If anyone has good theme suggestions or are great with design in general, please go ahead and add more themes. Light theme itself while now supported can still use more visual improvements.
Closes #237 
Resolves #238
> Feat: add toggle command for user to switch theme

- src/main/java/seedu/us/among/logic/commands/SendCommand.java
- src/main/java/seedu/us/among/logic/endpoint/Request.java
- src/main/java/seedu/us/among/ui/CommandBox.java
The cancelling of request was broken after recent PRs. The following changes were made to fix it as well as make a few improvements:
- `httpClient` attribute in `Request` is now properly assigned after a connection is established.
- `NoHttpResponseException` is now properly caught.
- `ctrl + d` is now used to cancel a request due to overlapping copy functionalities with `ctrl + c`.
Fixes #245
> Fix: minor refactor and fix bug with cancelling requests

- docs/UserGuide.md
Minor clean up to user guide to fix duplicates/missing information.
Closes #186
> Docs: clean up user guide

- src/main/java/seedu/us/among/logic/commands/AddCommand.java
- src/main/java/seedu/us/among/logic/commands/EditCommand.java
- src/main/java/seedu/us/among/logic/commands/RunCommand.java
- src/main/java/seedu/us/among/logic/parser/CliSyntax.java
- src/test/java/seedu/us/among/testutil/EndpointUtil.java
and made sure other command error msgs were properly formatted
The error is that if there is a space in PREFIX_METHOD and other prefixs, it will messes up how the index is parsed, and also messes up some functionalities like "edit 1 -t " in order to take away existing tags
closes #210
> Fix edit command error msg

- src/main/java/seedu/us/among/logic/commands/AddCommand.java
- src/main/java/seedu/us/among/logic/commands/EditCommand.java
- src/main/java/seedu/us/among/logic/commands/FindCommand.java
- src/main/java/seedu/us/among/logic/commands/RunCommand.java
- src/main/java/seedu/us/among/logic/parser/CliSyntax.java
- src/main/java/seedu/us/among/logic/parser/FindCommandParser.java
- src/main/java/seedu/us/among/model/endpoint/AddressContainsKeywordsPredicate.java
- src/main/java/seedu/us/among/model/endpoint/DataContainsKeywordsPredicate.java
- src/main/java/seedu/us/among/model/endpoint/EndPointContainsKeywordsPredicate.java
- src/main/java/seedu/us/among/model/endpoint/HeadersContainsKeywordsPredicate.java
- src/main/java/seedu/us/among/model/endpoint/MethodContainsKeywordsPredicate.java
- src/main/java/seedu/us/among/model/endpoint/TagsContainsKeywordsPredicate.java
- src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
- src/test/java/seedu/us/among/logic/commands/FindCommandTest.java
- src/test/java/seedu/us/among/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/us/among/logic/parser/ImposterParserTest.java
- src/test/java/seedu/us/among/model/ModelManagerTest.java
- src/test/java/seedu/us/among/testutil/EndpointUtil.java
Fixes #217 
Find command can now take in arguments such as -x -u -t ... 
Find command can now take in multiple keywords. 
Examples: 
`find -x METHOD` or find `-x METHOD METHOD` (in this case, will find both keywords)
`find -u URL`
and so on...
> Commands: Find Command Advanced Functionality

- src/main/java/seedu/us/among/logic/commands/AddCommand.java
- src/main/java/seedu/us/among/logic/commands/ListCommand.java
- src/main/java/seedu/us/among/model/EndpointList.java
- src/main/java/seedu/us/among/model/Model.java
- src/main/java/seedu/us/among/model/ModelManager.java
- src/main/java/seedu/us/among/model/endpoint/UniqueEndpointList.java
- src/main/java/seedu/us/among/ui/EndpointListPanel.java
- src/main/resources/view/EndpointListPanel.fxml
- src/test/java/seedu/us/among/logic/LogicManagerTest.java
- src/test/java/seedu/us/among/logic/commands/AddCommandTest.java
- src/test/java/seedu/us/among/logic/commands/ListCommandTest.java
ListCommand result is not helpful as it simply says all endpoints
listed. It does not account for the cases where there is no endpoints
saved.
Let's adjust the result output to prompt user to use show command if
there are endpoints saved, or use add command to add new endpoints.
This will make the result clearer to users.
I have also fixed the minor typos and clean up the numbering in
addCommand in order to allow users to easily copy paste the examples.
Some test cases are also fixed along the way.
screenshots:
Fixes: #298 
Fixes: #163
> Adjust ListCommand message

- src/main/resources/view/DarkTheme.css
- src/main/resources/view/EndpointListCard.fxml
- src/main/resources/view/ImposterTheme.css
- src/main/resources/view/LightTheme.css
Addresses #255.
Have made headers cyan in Imposter theme and orange in others instead of the initially proposed green.
> UI: Make headers look like tags

- src/main/java/seedu/us/among/logic/parser/FindCommandParser.java
How find should work: 
1. find -x get -x post (search: post) (in -x field only)
2. find get post (search: either get or post) (in all fields)
3. find -x get post (search: get in -x field) or (post in all fields)
4. find -x get -t cat (search: get in -x field and cat in -t field) (both must be present to show up)
> Command fixed another small bug with find

- src/main/java/seedu/us/among/logic/commands/EditCommand.java
- src/main/java/seedu/us/among/model/endpoint/Endpoint.java
- src/main/java/seedu/us/among/model/endpoint/UniqueEndpointList.java
- src/test/java/seedu/us/among/logic/commands/AddCommandTest.java
- src/test/java/seedu/us/among/model/endpoint/EndpointTest.java
Removes the `isSameEndpoint` method as it behaves the same as `equals`
Fixes #326
> Refactor isSameEndpoint method

- src/main/java/seedu/us/among/logic/commands/RunCommand.java
- src/main/java/seedu/us/among/logic/commands/SendCommand.java
- src/main/java/seedu/us/among/logic/request/EndpointCaller.java
Move exception handling for request into `EndpointCaller` to reduce repeated codes in `Send` and `Run`.
Resolves #340
> Refactor: move exception handling for request into EndpointCaller

- build.gradle
> Chore: enable assertions in build.gradle

- src/main/java/seedu/us/among/ui/ResultDisplay.java
There is a weird space before the word `Response`
Fixes: #396
> Remove a space in front of Response body wording

- docs/UserGuide.md
- src/main/java/seedu/us/among/ui/CommandBox.java
The last valid command is most likely to be repeated multiple times.
Let's add the ability to retrieve the last valid command for convenience.
By pressing ctrl + up-arrow in the command box, the last valid command (if any) will be set to the commandTextField.
Given that this is not really a command, I have added a miscellaneous section in UG under command to describe this behavior.
Fixes: #14
> Feature: Add ctrl + up-arrow feature to get last valid command

- src/main/java/seedu/us/among/ui/ResultDisplay.java
The new material theme introduced in #404 reused the gifs with white text meant for dark backgrounds; this PR is meant to change them to the ones with black text.
> UI: Fix wrong theme gifs in new material theme

- src/main/java/seedu/us/among/logic/commands/CommandResult.java
- src/main/java/seedu/us/among/logic/commands/ExitCommand.java
- src/main/java/seedu/us/among/logic/commands/HelpCommand.java
- src/main/java/seedu/us/among/logic/commands/ListCommand.java
- src/main/java/seedu/us/among/logic/commands/RunCommand.java
- src/main/java/seedu/us/among/logic/commands/SendCommand.java
- src/test/java/seedu/us/among/logic/commands/CommandResultTest.java
- src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
- src/test/java/seedu/us/among/logic/commands/ExitCommandTest.java
- src/test/java/seedu/us/among/logic/commands/HelpCommandTest.java
Multiple constructors repeat the same logic of attribute assignment and
force various command classes to define boolean variables just for the
sake of creating a command result.
Let's make one main private constructor and respective factory
constructor for specialised command results.
This helps remove all boolean attributes when creating a command result.
While it may not be the best practice (Enum could be used), the setting
of boolean attributes are within commandResult and hence less likely to
result in mistaken boolean values.
Fixes: #415
> Refactor CommandResult constructors

- docs/diagrams/BetterModelClassDiagram.puml
- docs/diagrams/ModelClassDiagram.puml
- docs/diagrams/StorageClassDiagram.puml
Remove AB3 references in model and storage component diagrams.
Add some missing classes.
Resolves #431
> Fix: minor fix to model and storage component diagrams in DG

- docs/index.md
Fix quickstart link in index page.
Add Apache HttpComponents to acknowledgements.
Closes #443
> Fix: fix quickstart link and acknowledge request library

- docs/UserGuide.md
Fix a few broken links.
Improve links in glossary to go to the specific term.
Closes #466
> Docs: fix broken links in UG

- src/main/java/seedu/us/among/ui/ResultDisplay.java
Trim API response feedback if it has more than 100000 chars (enforced as a maximum).
Fixes #530
> Fix: trim API response to enforce max 100000 chars

- src/main/java/seedu/us/among/commons/core/Messages.java
- src/main/java/seedu/us/among/logic/request/EndpointCaller.java
UnknownHostException and ConnectException now shows the same message to minimise confusion.
Note: This generic error message will be improved by @tlylt in a future PR.
Fixes #532
> Fix: standardise connection/unknownhost error messages to minimize confusion

- src/main/java/seedu/us/among/commons/core/Messages.java
- src/main/java/seedu/us/among/commons/util/StringUtil.java
- src/main/java/seedu/us/among/logic/commands/EditCommand.java
- src/main/java/seedu/us/among/logic/commands/RemoveCommand.java
- src/main/java/seedu/us/among/logic/commands/SendCommand.java
- src/main/java/seedu/us/among/logic/commands/ShowCommand.java
- src/main/java/seedu/us/among/logic/parser/ParserUtil.java
- src/main/java/seedu/us/among/logic/parser/ShowCommandParser.java
- src/test/java/seedu/us/among/logic/LogicManagerTest.java
- src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
- src/test/java/seedu/us/among/logic/commands/RemoveCommandTest.java
- src/test/java/seedu/us/among/logic/commands/SendCommandTest.java
- src/test/java/seedu/us/among/logic/commands/ShowCommandTest.java
- src/test/java/seedu/us/among/logic/parser/ParserUtilTest.java
- src/test/java/seedu/us/among/logic/parser/ShowCommandParserTest.java
- use BigInteger to parse string input for index
- show command error message has been updated as follows:
- will proceed to update other command error messages such that cause of error is shown in the first line, followed by a standard command usage note
- fixes #498 , fixes #485
> Update integer parsing and show command fixes
